# Generated by Django 5.2.11 on 2026-02-17 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('avg_fatigue', models.FloatField()),
                ('avg_stress', models.FloatField()),
                ('avg_attention', models.FloatField()),
                ('avg_workload', models.FloatField()),
                ('max_fatigue', models.FloatField()),
                ('max_stress', models.FloatField()),
                ('min_attention', models.FloatField()),
                ('max_workload', models.FloatField()),
                ('total_alerts', models.IntegerField(default=0)),
                ('critical_alerts', models.IntegerField(default=0)),
                ('overall_performance', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('recommendations', models.TextField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='monitoring.monitoringsession')),
            ],
            options={
                'db_table': 'session_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file_path', models.FileField(upload_to='datasets/')),
                ('total_samples', models.IntegerField(default=0)),
                ('feature_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_datasets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('fatigue', 'Fatigue Detection'), ('stress', 'Stress Detection'), ('attention', 'Attention Detection'), ('workload', 'Workload Detection')], max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('training', 'Training'), ('active', 'Active'), ('archived', 'Archived')], default='training', max_length=20)),
                ('algorithm', models.CharField(max_length=100)),
                ('model_file', models.FileField(upload_to='ml_models/')),
                ('scaler_file', models.FileField(blank=True, null=True, upload_to='ml_models/')),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('training_samples', models.IntegerField(default=0)),
                ('training_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_models',
                'ordering': ['-created_at'],
                'unique_together': {('model_type', 'version')},
            },
        ),
    ]
