# Generated by Django 5.2.11 on 2026-02-17 15:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('flight', 'Real Flight'), ('simulator', 'Simulator'), ('training', 'Training')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='active', max_length=20)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('aircraft_type', models.CharField(blank=True, max_length=100)),
                ('flight_number', models.CharField(blank=True, max_length=50)),
                ('route', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitoring_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MentalStateAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('fatigue_score', models.FloatField()),
                ('stress_score', models.FloatField()),
                ('attention_score', models.FloatField()),
                ('workload_score', models.FloatField()),
                ('overall_risk', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=20)),
                ('alert_triggered', models.BooleanField(default=False)),
                ('alert_type', models.CharField(blank=True, max_length=50)),
                ('alert_message', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='monitoring.monitoringsession')),
            ],
            options={
                'db_table': 'mental_state_assessments',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('alert_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_details', to='monitoring.mentalstateassessment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.monitoringsession')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('eeg_channel_1', models.FloatField(blank=True, null=True)),
                ('eeg_channel_2', models.FloatField(blank=True, null=True)),
                ('eeg_channel_3', models.FloatField(blank=True, null=True)),
                ('eeg_channel_4', models.FloatField(blank=True, null=True)),
                ('eeg_channel_5', models.FloatField(blank=True, null=True)),
                ('eeg_channel_6', models.FloatField(blank=True, null=True)),
                ('eeg_channel_7', models.FloatField(blank=True, null=True)),
                ('eeg_channel_8', models.FloatField(blank=True, null=True)),
                ('ecg_heart_rate', models.FloatField(blank=True, null=True)),
                ('ecg_hrv', models.FloatField(blank=True, null=True)),
                ('ecg_rr_interval', models.FloatField(blank=True, null=True)),
                ('eye_blink_rate', models.FloatField(blank=True, null=True)),
                ('eye_fixation_duration', models.FloatField(blank=True, null=True)),
                ('eye_saccade_velocity', models.FloatField(blank=True, null=True)),
                ('pupil_diameter', models.FloatField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sensordevice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='monitoring.monitoringsession')),
            ],
            options={
                'db_table': 'sensor_readings',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='mentalstateassessment',
            index=models.Index(fields=['session', 'timestamp'], name='mental_stat_session_54eca4_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['session', 'timestamp'], name='sensor_read_session_3dc362_idx'),
        ),
    ]
